---

#################################################################

- name: "bash > config > .bashrc"
  with_items:
    - "{{ all_users }}"
  template:
    src   : "bashrc.j2"
    dest  : "{{ item.home }}/.bashrc"
    owner : "{{ item.id }}"
    group : "{{ item.id }}"
    mode  : "0644"
  tags:
    - "{{ shell.tags }}"

- name: "bash > config > .bash_aliases"
  with_items:
    - "{{ all_users }}"
  template:
    src   : "bash_aliases.j2"
    dest  : "{{ item.home }}/.bash_aliases"
    owner : "{{ item.id }}"
    group : "{{ item.id }}"
    mode  : "0644"
  tags:
    - "{{ shell.tags }}"

- name: "bash > config > .bash_functions"
  with_items:
    - "{{ all_users }}"
  template:
    src   : "bash_functions.j2"
    dest  : "{{ item.home }}/.bash_functions"
    owner : "{{ item.id }}"
    group : "{{ item.id }}"
    mode  : "0644"
  tags:
    - "{{ shell.tags }}"

- name: "bash > config > .bash_welcome"
  with_items:
    - "{{ all_users }}"
  when    : bash_welcome != ""
  copy:
    src   : "welcome_{{ bash_welcome }}"
    dest  : "{{ item.home }}/.bash_welcome"
    owner : "{{ item.id }}"
    group : "{{ item.id }}"
    mode  : "0644"
  tags:
    - "{{ shell.tags }}"

- name: "bash > config > .bash_proxy"
  with_items:
    - "{{ all_users }}"
  template:
    src   : "bash_proxy.j2"
    dest  : "{{ item.home }}/.bash_proxy"
    owner : "{{ item.id }}"
    group : "{{ item.id }}"
    mode  : "0644"
  tags:
    - "{{ shell.tags }}"
    - "proxy"

#################################################################

- name: "inputrc > disable bell"
  lineinfile:
    path    : "/etc/inputrc"
    regexp  : "set bell-style visible"
    line    : "set bell-style visible"
  tags:
    - "{{ shell.tags }}"

#################################################################

