---

libraries_apt:
  - python-pip        # Package Manager - Python
  - snapd             # Package Manager - Unified Linux
  - git               # Source Control
  - curl              # Api Tool
  - wget              # Remote resource pull
  - tree              # Dir Structure tree
  - jq                # Json Parser
  - xclip             # Store to Clipboard
  - gawk              # Extended awk

libraries_pip:
  - yq                # Yaml Parser

libraries_snap:
  - p7zip-desktop     # Archiver
  - htop              # Memory viewer

libraries_apt_gui:
  - baobab            # Disk Usage
  - shutter           # Snipping Tool
  - vlc               # Media Player
  - gedit             # Text Editor

libraries_pip_gui: []

libraries_snap_gui: []

