---

libraries_apt:
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "gnupg-agent"
  - "software-properties-common"

docker:
  key_server  : "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  key_id      : "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
  repo        : "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
  apts:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"

docker_compose:
  url         : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
  dest        : "/usr/local/bin/docker-compose"

