---

- hosts         : localhost
  become        : yes
  become_method : sudo
  gather_facts  : yes
  connection    : local

  vars:
    - proxy     : False
      has_gui   : True

      all_users:
        - "{{ root_user     }}"
        - "{{ primary_user  }}"


  roles:
    - { role: checks                                                                                            }
    - { role: users                                                                                             }
    - { role: desktop                                                                                           }
    - { role: prereq                                                                                            }


    - { role: network/dns                                                                                       }
    - { role: network/forticlient                                                                               }

    - { role: git                                                                                               }
    - { role: ssh                                                                                               }
    - { role: bash                                                                                              }
    - { role: vim                                                                                               }
    - { role: powerline                                                                                         }
    - { role: general                                                                                           }
    - { role: java                                                                                              }
    - { role: keychain                                                                                          }
    - { role: wallpaper                                                                                         }
    - { role: system-monitor                                                                                    }
    - { role: browser/chrome                                                                                    }
    - { role: browser/firefox                                                                                   }
    - { role: terminator                                                                                        }

    - { role: developer/general                                                                                 }
    - { role: developer/gradle                                                                                  }
    - { role: developer/maven                                                                                   }
    - { role: developer/postman                                                                                 }

    - { role: developer/terraform,      terraform_version   : "0.11.7"                                          }
    - { role: developer/docker                                                                                  }
    - { role: developer/awscli                                                                                  }




    - { role: developer/ide/intellij                                                                            }
    - { role: developer/ide/pycharm                                                                             }
    - { role: developer/ide/android                                                                             }
    - { role: developer/ide/mongorobot3                                                                         }

    - { role: media/steam                                                                                       }
    - { role: media/plex                                                                                        }

